apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmstreet.fullname" . }}
  namespace: {{ .Valuses.namespacesOverride | include "helmstreet.serviceAccountName" . }}
  labels:
    {{- include "helmstreet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmstreet.selectorLabels" . | nindent 4 }}
