apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firstextermal
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/attiferosisal/argocd-test-private.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://129.153.169.34:6443
    namespace: default