apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: firstcrd-ngix
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: test app nginx
  # Allow manifests to deploy from area-riservata-italia
  sourceRepos:
    - "*"
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: 'default'
      server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  #namespaceResourceBlacklist:
  #  - group: ""
  #    kind: ResourceQuota
  #  - group: ""
  #    kind: LimitRange
  #  - group: ""
  #    kind: NetworkPolicy
  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  #namespaceResourceWhitelist:
  #  - group: "*"
  #    kind: "*"
  #roles: []
