apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: mycluster
  server: https://129.153.169.34:6443
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }