apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firstcrd-ngix
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/attiferosisal/applicationtest.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default