apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd-2-4
spec:
  project: default
  source:
    chart: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.2.13
    helm:
      releaseName: nginx-test
  destination:
    server: "https://kubernetes.default.svc"
    namespace: helmstreet-incubo