apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmstreet-application
  namespace: argocd-2-4
spec:
  destination:
    namespace: default
    #server: https://kubernetes.default.svc
    server: https://129.153.169.34:6443
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helmstreet/preprod
    repoURL: https://github.com/attiferosisal/argocd-test.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true