image:
  tag: 2.4.11

#controller: 
#  metrics:
#    enabled: true

redis:
  #enabled: ture
  architecture: replication

redisWait:
  enabled: ture

server:
  replicaCount: 1
  insecure: true # important because otherwise argocd make a redirect
  url: https://argocd-automation-platform-preprod.sisal.it


repoServer:
  replicaCount: 2
  #livenessProbe:
  #  enabled: true
  #readinessProbe:
  #  enabled: true
  #metrics:
  #  enabled: true

dex:
  enabled: true
  #metrics:
  #  enabled: true
  serviceAccount:
    name: argocd-dex-server
    create: false

rbac:
  create: false


  
