image:
  tag: 2.4.11-debian-11-r5

#controller: 
#  metrics:
#    enabled: true

redis:
  #enabled: ture
  architecture: replication

server:
  replicaCount: 2
  insecure: true # important because otherwise argocd make a redirect
  url: https://argocd-automation-platform-preprod.sisal.it
  
repoServer:
  replicaCount: 2
  #livenessProbe:
  #  enabled: true
  #readinessProbe:
  #  enabled: true
  #metrics:
  #  enabled: true

dex:
  enabled: false
  #metrics:
  #  enabled: true
  
