
extraDeploy:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: oci-kubeconfig
      namespace: argocd-update
    data:
      appsettings.json: |-
        {
          "AllowedHosts": "*"
        }
repoServer:
  extraVolumeMounts:
    - name: ocicli
      mountPath: /app/config/ocicli
      readOnly: true
  extraVolumes:
    - name: ocicli
      emptyDir: {}


# 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
      - name: custom-tools
        emptyDir: {}
      # 2. Use an init container to download/copy custom binaries into the emptyDir
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        args:
        - wget -qO- https://storage.googleapis.com/kubernetes-helm/helm-v2.12.3-linux-amd64.tar.gz | tar -xvzf - &&
          mv linux-amd64/helm /custom-tools/
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /usr/local/bin/helm
          name: custom-tools
          subPath: helm